sudo: required
language: java
jdk: openjdk8
before_install:
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get -q update
  - sudo apt-get -y install openjdk-6 openjdk-7
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
script:
  - jdk_switcher use openjdk6
  - export JAVA6_HOME=$JAVA_HOME
  - jdk_switcher use openjdk7
  - export JAVA7_HOME=$JAVA_HOME
  - jdk_switcher use openjdk8
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V "-Djdk.6.rt.jar.path=$JAVA6_HOME/jre/lib/rt.jar" "-Djdk.7.rt.jar.path=$JAVA7_HOME/jre/lib/rt.jar"
