dist: trusty
language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk: openjdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
script:
  - jdk_switcher use openjdk6
  - export JAVA6_HOME=$JAVA_HOME
  - jdk_switcher use openjdk7
  - export JAVA7_HOME=$JAVA_HOME
  - jdk_switcher use openjdk8
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V "-Djdk.6.rt.jar.path=$JAVA6_HOME/jre/lib/rt.jar" "-Djdk.7.rt.jar.path=$JAVA7_HOME/jre/lib/rt.jar"
