dist: trusty
language: java
jdk: openjdk9
cache:
  directories:
    - $HOME/.m2
# Delete artifacts that we build to prevent old and incorrect files from
# breaking the current build.
before_cache:
  - rm --force --recursive $HOME/.m2/repository/net/sourceforge/argparse4j
install: skip
script:
  - mvn install -Dgpg.skip -B -V
