dist: trusty
language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk: openjdk9
install:
- export JAVA9_HOME=$JAVA_HOME
- jdk_switcher use openjdk6
- export JAVA6_HOME=$JAVA_HOME
- jdk_switcher use openjdk7
- export JAVA7_HOME=$JAVA_HOME
- export JAVA_HOME=$JAVA9_HOME
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
